name: Scan Containers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        
    - name: Run Trivy Scan
      env:
        CONTAINER_IMAGE_NAME: test-image:latest
        TRIVY_CACHE_DIR: /tmp/trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.32.0/trivy_0.32.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.32.0_Linux-64bit.deb
        trivy image "$CONTAINER_IMAGE_NAME" -f json -o trivy-results.json
        trivy fs your-container-directory -f json -o trivy-fs-results.json
        trivy image --security-checks vuln "$CONTAINER_IMAGE_NAME" -f json -o trivy-vuln-results.json
        trivy image --security-checks secret "$CONTAINER_IMAGE_NAME" -f json -o trivy-secret-results.json
        
    - name: Upload Trivy Scan Results
      uses: actions/upload-artifact@v3
      with:
        name: trivy-results
        path: |
          trivy-results.json
          trivy-fs-results.json
          trivy-vuln-results.json
          trivy-secret-results.json
